### ISSUE TITLE
Transaction processing error on Test-Net transaction in Block 14388081

### ISSUE THREAD

**Issue by HerbertJordan** [Fantom-foundation/Tosca#857]
A transaction in block 14388081 of the test net triggered the following panic:
```
panic: worker 3 recovered panic; gas pool pushed above uint64
goroutine 67 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/Fantom-foundation/Aida/executor.(*executor[...]).runTransactions.func2.1()
        /home/lj/Aida/executor/executor.go:450 +0xaa
panic({0x120f860?, 0x16b5950?})
        /usr/local/go/src/runtime/panic.go:770 +0x132
github.com/Fantom-foundation/go-opera/evmcore.(*GasPool).AddGas(...)
        /home/lj/Aida/sonic/evmcore/gaspool.go:31
github.com/Fantom-foundation/go-opera/evmcore.(*StateTransition).refundGas(0xc008942480, 0x6eb578a669c358f0?)
        /home/lj/Aida/sonic/evmcore/state_transition.go:334 +0x14b
github.com/Fantom-foundation/go-opera/evmcore.(*StateTransition).TransitionDb(0xc008942480)
        /home/lj/Aida/sonic/evmcore/state_transition.go:310 +0x658
github.com/Fantom-foundation/go-opera/evmcore.ApplyMessage(0x1567338?, 0x1567340?, 0xc006f1e000?)
        /home/lj/Aida/sonic/evmcore/state_transition.go:172 +0x1c
github.com/Fantom-foundation/Aida/executor.applyMessageUsingSonic({0x7f03ac7b5840, 0xc006f638f0}, 0xc0089b02c0, 0xc006f63960, {0x16d01c0, 0xc00894e3f0}, 0xc005314dd0, {0x0, 0x1, 0x0, ...})
        /home/lj/Aida/executor/transaction_processor.go:302 +0x433
github.com/Fantom-foundation/Aida/executor.(*aidaProcessor).processRegularTx(_, {_, _}, _, _, {_, _})
```

Command to reproduce the issue (requires access to an testnet Aida DB):
```
./build/aida-vm --aida-db /mnt/aida-db-testnet/aida-db --chainid 4002 --vm-impl lfvm 14388081 14388081
```

When switching to the `geth` based interpreter, the transaction is processed flawlessly:
```
/build/aida-vm --aida-db /mnt/aida-db-testnet/aida-db --chainid 4002 --vm-impl geth 14388081 14388081
```

**Comment by simonlechner** [comment]
With the newest main version in both Aida and Tosca this error is no longer reproducible. A successful run of the testnet history can be found on [jenkins](https://scala.fantom.network/job/Tosca/job/Validate-LFVM/165/).
